### ISSUE TITLE
Does this work for Shelly 3EM, too?

### ISSUE THREAD

**Issue by DDvO** [sicanins/shelly-pro3EM-energycounter#5]
Or is there a recommendation for a similar script elsewhere?

**Comment by sicanins** [comment]
Hi, as far as I know the "normal" 3EM does not support Shelly script, means no. That is exactly the selling point of the Pro 3EM..

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: David von Oheimb ***@***.***>
Sent: Monday, April 15, 2024 8:23:15 PM
To: sicanins/shelly-pro3EM-energycounter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sicanins/shelly-pro3EM-energycounter] Does this work for Shelly 3EM, too? (Issue #5)


Or is there a recommendation for a similar script elsewhere?

**Comment by DDvO** [comment]
Good to know - thank you for you swift reaction!
